### ISSUE TITLE
Fruits table - first steps with PostgreSQL

### ISSUE THREAD

**Issue by karastoyanov** [Stake-And-Rope/uni-database-project#5]
:one: Create a new table named `fruits` with the following columns:
* `fruit_id` --> data type: INT4
* `fruit_name` --> data type: VARCHAR (same as string), :warning: consider the max length of the data inside this field when setting the data type with VARCHAR, e.g. VARCHAR(10) will give you max 10 symbols string.
* `price` --> data type: DECIMAL number (same as float), with two decimal places.
* `stock_quantity` --> data type: DECIMAL number with two decimal places.
* `stock_value` --> data type: DECIMAL. This column should use a formula to calculate the total value (`stock_value` = `price` * `stock_quantity`)

:bulb: You can add any other colums by your choice to make the table more informative. 

:two: Create SQL query to add some data inside the table, for example:
`fruit_id` : 1000
`fruit_name` : orange
`price` : 2.50
`stock_quantity`: 10.00
`stock_value`: use the formula `price` * `stock_quantity`

* Add few records inside the table. 

:three: Try few CRUD(Create, Read, Update, Delete) operations

* Play around with the table. You can try to add/delete/modify colums and records. Upload below as comments or files the SQL statements you've used for the task.

:sos:  Here's the [Postgre documentation](https://www.postgresql.org/docs/15/sql.html) for further support.

**Comment by rayapetkova** [comment]
Added a new column "rate" which shows how tasty is each fruit in the table from 1 to 10.

[fruits.txt](https://github.com/karastoyanov/uni-database-project/files/11361164/fruits.txt)

**Comment by karastoyanov** [comment]
So far so good. Next step is to create two new tables:

:one: Create table `customers` with columns:
* `customer_id` - INT, PRIMARY KEY
* `first_name` - VARCHAR
* `last_name` - VARCHAR
* `registration_date` - default value current date/hour
and insert some data inside the table. You can add any additional columns by your choice

:two: Create another table `orders` with colums:
* `order_id` INT, PRIMARY KEY
* `customer_id` INT
* `customer_name` VARCHAR
* `products` ARRAY --> Check [this](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-array/) link for more info
* `order_value` NUMERIC
* `order_date` default value current date/hour

After we have this structure, we will begin writing some Python scripts which we will use to create new records inside the tables.

**Comment by rayapetkova** [comment]
Added a new column "money_on_hand" in the first table "customers".

[customers_and_orders.txt](https://github.com/Stake-And-Rope/uni-database-project/files/11365155/customers_and_orders.txt)

**Comment by karastoyanov** [comment]
I am closing this Issue and we are moving to the new project in [market-app](https://github.com/orgs/Stake-And-Rope/projects/2/views/1)
